name: Deploy minecraft server in balena cloud
on:
  push:
    branches:
      - master
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2.4.0
      - run: wget https://github.com/balena-io/balena-cli/releases/download/v12.55.1/balena-cli-v12.55.1-linux-x64-standalone.zip
      - run: unzip balena-cli-v12.55.1-linux-x64-standalone.zip
      - uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["**/*.properties", "**/*.sh", "**/.bashrc"]'
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          RCON_PASSWORD: ${{ secrets.RCON_PASSWORD }}
      - run: ./balena-cli/balena login --token ${{ secrets.BALENA_TOKEN }}
      - run: ./balena-cli/balena push minecraft
